src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/AuthorizationPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.DependencyInjection;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class AdminUserInfoAuthorizationPageModel : BaseAdminPageModel
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly SysRoleAdminUserInfoService sysRoleAdminUserInfoService;

        public AdminUserInfoAuthorizationPageModel(IServiceProvider _serviceProvider, SysRoleAdminUserInfoService sysRoleAdminUserInfoService)
        {
            this._serviceProvider = _serviceProvider;
            this.sysRoleAdminUserInfoService = sysRoleAdminUserInfoService;
        }

        public IEnumerable<SysRoleAdminUserInfoDto> RoleAdminUserInfoDtos { get; set; }

        public async Task OnGetAsync(int accountId)
        {
            AdminUserInfoService adminUserInfoService = _serviceProvider.GetService<AdminUserInfoService>();
            SysRoleService sysRoleService = _serviceProvider.GetService<SysRoleService>();
            //SysRoleAdminUserInfoService sysRoleAdminUserInfoService = _serviceProvider.GetService<SysRoleAdminUserInfoService>();

            IEnumerable<SysRole> sysRoles = await sysRoleService.GetFullListAsync(_ => true);
            IEnumerable<SysRoleAdminUserInfo> sysRoleAdminUserInfos = await sysRoleAdminUserInfoService.GetFullListAsync(_ => _.AccountId == accountId);

            IEnumerable<SysRoleAdminUserInfoDto> dto = from _ in sysRoles
                                                       join __ in sysRoleAdminUserInfos
                                                       on _.Id equals __.RoleId into __Left
                                                       from __ in __Left.DefaultIfEmpty()
                                                       select new SysRoleAdminUserInfoDto()
                                                       {
                                                           AdminAccountId = accountId,
                                                           HasRole = __ != null,
                                                           RoleId = _.Id,
                                                           RoleName = _.RoleName
                                                       };
            RoleAdminUserInfoDtos = dto;
        }

        public async Task<IActionResult> OnPostAsync(IEnumerable<string> RoleIds, int accountId)
        {
            if (!RoleIds.Any() || accountId <= 0)
            {
                return Ok(false);
            }
            await sysRoleAdminUserInfoService.AddAsync(RoleIds, accountId);
            return Ok(true);
        }
    }
}

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.CO2NET.Extensions;
using Senparc.Core.Models;
using Senparc.Ncf.Core.Enums;
using Senparc.Ncf.Core.Models;
using Senparc.Ncf.Core.Validator;
using Senparc.Ncf.Service;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class AdminUserInfo_EditModel : BaseAdminPageModel, IValidatorEnvironment
    {
        /// <summary>
        /// Id
        /// </summary>
        [BindProperty]
        public int Id { get; set; }

        public bool IsEdit { get; set; }


        [BindProperty]
        public CreateOrUpdate_AdminUserInfoDto AdminUserInfo { get; set; } = new CreateOrUpdate_AdminUserInfoDto();
        //public CreateUpdate_AdminUserInfoDto AdminUserInfo { get; set; }

        private readonly AdminUserInfoService _adminUserInfoService;


        public AdminUserInfo_EditModel(AdminUserInfoService adminUserInfoService)
        {
            _adminUserInfoService = adminUserInfoService;
        }

        public IActionResult OnGet(int id)
        {
            IsEdit = id > 0;
            if (IsEdit)
            {
                AdminUserInfo = _adminUserInfoService.GetAdminUserInfo(id);
                if (AdminUserInfo == null)
                {
                    throw new Exception("信息不存在！");//TODO:临时
                    //return RenderError("信息不存在！");
                }
             
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            IsEdit = Id > 0;
            this.Validator(AdminUserInfo.UserName, "用户名", "UserName", false)
                .IsFalse(z => this._adminUserInfoService.CheckUserNameExisted(Id, z), "用户名已存在！", true);
            if (!IsEdit)
            {

                this.Validator(AdminUserInfo.Password, "密码", "Password", false).MinLength(6);
            }
            else
            {
                if (!AdminUserInfo.Password.IsNullOrEmpty())
                {
                    this.Validator(AdminUserInfo.Password, "密码", "Password", false).MinLength(6);
                }
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (IsEdit)
            {
                AdminUserInfo.Id = Id;
                _adminUserInfoService.UpdateAdminUserInfo(AdminUserInfo);
            }
            else
            {
                _adminUserInfoService.CreateAdminUserInfo(AdminUserInfo);
            }

            base.SetMessager(MessageType.success, $"{(IsEdit ? "修改" : "新增")}成功！");
            return RedirectToPage("./Index");
        }
    }
}

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Senparc.Core.Models;
using Senparc.Ncf.Core.Enums;
using Senparc.Ncf.Core.Models;
using Senparc.Ncf.Service;
using Senparc.Ncf.Utility;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class AdminUserInfo_IndexModel : BaseAdminPageModel
    {
        private readonly AdminUserInfoService _adminUserInfoService;
        public PagedList<AdminUserInfo> AdminUserInfoList { get; set; }

        /// <summary>
        /// 属性绑定，支持GET
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; } = 1;

        /// <summary>
        /// 排序方法
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public string OrderField { get; set; } = "AddTime Desc,Id";

        public AdminUserInfo_IndexModel(AdminUserInfoService adminUserInfoService)
        {
            _adminUserInfoService = adminUserInfoService;
        }

        //[Filters.CustomerResourceFilter("Add")]
        public async Task<IActionResult> OnGetAsync()
        {
            var seh = new SenparcExpressionHelper<AdminUserInfo>();
            var where = seh.BuildWhereExpression();
            var admins = await _adminUserInfoService.GetObjectListAsync(PageIndex, 20, where, OrderField);
            AdminUserInfoList = admins;
            return null;
        }

        public IActionResult OnPostDemo()
        {
            return Ok(null);
        }

        public IActionResult OnPost(int[] ids)
        {
            foreach (var id in ids)
            {
                _adminUserInfoService.DeleteObject(id);
            }

            return RedirectToPage("./Index");
        }
    }
}

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/Menu/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Ncf.Core.Models;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class MenuEditModel : BaseAdminPageModel
    {
        private readonly SysMenuService _sysMenuService;
        private readonly SysButtonService _sysButtonService;

        public MenuEditModel(SysMenuService _sysMenuService, SysButtonService _sysButtonService)
        {
            CurrentMenu = "Menu";
            this._sysMenuService = _sysMenuService;
            this._sysButtonService = _sysButtonService;
        }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        public SysMenuDto SysMenuDto { get; set; }

        public IEnumerable<SysButton> SysButtons { get; set; }

        public async Task OnGetAsync()
        {
            if (!string.IsNullOrEmpty(Id))
            {
                var entity = await _sysMenuService.GetObjectAsync(_ => _.Id == Id);
                SysButtons = await _sysButtonService.GetFullListAsync(_ => _.MenuId == Id);

                SysMenuDto = _sysMenuService.Mapper.Map<SysMenuDto>(entity);
            }
            else
            {
                SysMenuDto = new SysMenuDto() { Visible = true };
                SysButtons = new List<SysButton>() { new SysButton() };
            }
        }

        public async Task<IActionResult> OnGetDetailAsync(string id)
        {
            var entity = await _sysMenuService.GetObjectAsync(_ => _.Id == Id);
            var sysMenuDto = _sysMenuService.Mapper.Map<SysMenuDto>(entity);
            var sysButtons = await _sysButtonService.GetFullListAsync(_ => _.MenuId == Id);
            return Ok( new{ sysMenuDto, sysButtons });
        }

        /// <summary>
        /// 获取菜单
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnGetMenuAsync()
        {
            return Ok(await _sysMenuService.GetMenuDtoByCacheAsync());
        }

        /// <summary>
        /// 获取菜单下的按钮
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnGetButtonsAsync(string menuId)
        {
            return Ok(await _sysButtonService.GetSysButtonDtosAsync(menuId));
        }

        public async Task<IActionResult> OnPostDeleteButtonAsync(string buttonId)
        {
            if (string.IsNullOrEmpty(buttonId))
            {
                return Ok(false);
            }
            await _sysButtonService.DeleteObjectAsync(_ => _.Id == buttonId);
            return Ok(true);
        }

        public async Task<IActionResult> OnPostDeleteAsync(string[] ids)
        {
            var entity = await _sysMenuService.GetFullListAsync(_ => ids.Contains(_.Id));
            var buttons = await _sysButtonService.GetFullListAsync(_ => ids.Contains(_.MenuId));

            await _sysButtonService.DeleteAllAsync(buttons);
            await _sysMenuService.DeleteAllAsync(entity);
            await _sysMenuService.RemoveMenuAsync();
            return Ok(true);
        }

        public async Task<IActionResult> OnPostAddMenuAsync(SysMenuDto sysMenu)
        {
            if (string.IsNullOrEmpty(sysMenu.MenuName))
            {
                return Ok("菜单名称不能为空", false, "菜单名称不能为空");
            }
            var entity = await _sysMenuService.CreateOrUpdateAsync(sysMenu);
            return Ok(entity.Id);
        }

        public async Task<IActionResult> OnPostAsync(SysMenuDto sysMenuDto, IEnumerable<SysButtonDto> buttons)
        {
            if (!ModelState.IsValid)
            {
                return Ok("模型验证未通过", false, "模型验证未通过");
            }

            await _sysMenuService.CreateOrUpdateAsync(sysMenuDto, buttons);

            return Ok(new { buttons, sysMenuDto });
        }
    }
}

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class RoleEditModel : BaseAdminPageModel
    {
        private readonly SysRoleService _sysRoleService;

        public RoleEditModel(SysRoleService sysRoleService)
        {
            CurrentMenu = "Role";
            _sysRoleService = sysRoleService;
        }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        [BindProperty]
        public SysRoleDto SysRoleDto { get; set; }

        public async Task OnGetAsync()
        {
            if (!string.IsNullOrEmpty(Id))
            {
                var entity = await _sysRoleService.GetObjectAsync(_ => _.Id == Id);
                SysRoleDto = _sysRoleService.Mapper.Map<SysRoleDto>(entity);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //if (!string.IsNullOrEmpty(Id))
            //{
            //    var entity = await _sysRoleService.GetObjectAsync(_ => _.Id == Id);
            //    SysRoleDto = _sysRoleService.Mapper.Map<SysRoleDto>(entity);
            //}
            await _sysRoleService.CreateOrUpdateAsync(SysRoleDto);
            return RedirectToPage("./Index");
        }
    }
}

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/AuthorizationPage.cshtml
@page
@model Senparc.Areas.Admin.Areas.Admin.Pages.AdminUserInfoAuthorizationPageModel
@{
    ViewData["Title"] = "角色授予";
}


@section breadcrumbs{
    <li>系统管理</li>
    <li>
        <a asp-Page="/AdminUserInfo">管理员管理</a>
    </li>
    <li>
        @ViewData["Title"]
    </li>
}

<div class="row">
    <div class="x_panel">
        <div class="x_content">
            @foreach (var item in Model.RoleAdminUserInfoDtos)
            {
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="checkbox">
                        <label>
                            <input value="@item.RoleId" name="" type="checkbox" @(item.HasRole ? "checked" : "") class="flat roleCheckBox"> @item.RoleName
                        </label>
                    </div>
                </div>
            }
            <hr />
            <div class="col-md-12 col-sm-12 col-xs-12">
                <a class="btn btn-default" asp-page="./Index">返回</a>
                <a class="btn btn-success" id="submit">保存</a>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/Admin/Pages/AdminUserInfo/AuthorizationPage.js"></script>
}

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/Edit.cshtml
@page

@model Senparc.Areas.Admin.Areas.Admin.Pages.AdminUserInfo_EditModel
@{
    ViewData["Title"] = $"{(Model.IsEdit ? "编辑" : "新增")}管理员";
}


@section breadcrumbs{
    <li>
        <a asp-Page="/AdminUserInfo">管理员管理</a>
    </li>
    <li>
        @ViewData["Title"]
    </li>
}
<!-- START row-->

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <form class="form-horizontal form-label-left" novalidate method="post">
                    <input type="hidden" asp-for="Id" />
                    <div style="position:absolute;left:-9999px">
                        <input name="old-userName" type="text">
                        <input name="old-pwd" type="password">
                    </div>
                    @*<p>
                            For alternative validation library <code>parsleyJS</code> check out in the <a href="form.html">form page</a>
                        </p>*@
                    @*<span class="section">Personal Info</span>*@
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">
                            用户名 @*<span class="required">*</span>*@
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="AdminUserInfo.UserName" class="form-control col-md-7 col-xs-12" data-validate-length="1,20" placeholder="请输入用户名" required="required" type="text">
                            不建议修改用户名！
                            <span asp-validation-for="AdminUserInfo.UserName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label for="password" class="control-label col-md-3">密码</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="AdminUserInfo.Password" type="password" data-validate-length="5,12" class="form-control col-md-7 col-xs-12" placeholder="请输入密码">
                            <span asp-validation-for="AdminUserInfo.Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label for="password2" class="control-label col-md-3 col-sm-3 col-xs-12">再次确认密码</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input id="password2" type="password" data-validate-linked="password" class="form-control col-md-7 col-xs-12" placeholder="请再次输入密码">
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            真实姓名
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="AdminUserInfo.RealName" type="text" class="form-control col-md-7 col-xs-12" placeholder="请输入真实姓名">
                            <span asp-validation-for="AdminUserInfo.RealName" class="text-danger"></span>

                            @*<textarea id="textarea" name="textarea" class="form-control col-md-7 col-xs-12"></textarea>*@
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            手机号
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="AdminUserInfo.Phone" type="text" class="form-control col-md-7 col-xs-12" placeholder="请输入手机号">
                            <span asp-validation-for="AdminUserInfo.Phone" class="text-danger"></span>

                            @*<textarea id="textarea" name="textarea" class="form-control col-md-7 col-xs-12"></textarea>*@
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            备注
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="AdminUserInfo.Note" type="text" class="form-control col-md-7 col-xs-12" placeholder="请输入备注信息" multiple="multiple">
                            <span asp-validation-for="AdminUserInfo.Note" class="text-danger"></span>

                            @*<textarea id="textarea" name="textarea" class="form-control col-md-7 col-xs-12"></textarea>*@
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            <a asp-page="./Index" class="btn btn-primary">取消</a>
                            <button id="send" type="submit" class="btn btn-success">提交</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/Extensions/Tests/Senparc.Xncf.ChangeNamespace.Tests/App_Data/src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/Index.cshtml
@page "{handler?}"
@model Senparc.Areas.Admin.Areas.Admin.Pages.AdminUserInfo_IndexModel
@addTagHelper *, Senparc.Areas.Admin
@using System.Web.Mvc
@{
    ViewData["Title"] = "管理员管理";
}
@section breadcrumbs{
    <li>系统管理</li>
    <li>
        管理员管理
    </li>
}
<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="pull-left">
                <a PermissionCode="Add" asp-page="Edit" asp-route-id="" title="新增" class="btn-sm btn btn-success">
                    <em class="fa fa-plus"></em> &nbsp;<small>新增</small>
                </a>
                <label for="deleteBtn" class="btn-sm btn btn-danger" title="删除">
                    <em class="fa fa-trash-o"></em> &nbsp;<small>删除</small>
                    <input type="submit" id="deleteBtn" onclick="deleteCheck('ids','deleteForm'); return false;" form="deleteForm" class="hidden" value="删除" />
                </label>
            </div>
            <div class="clearfix"></div>
            <div class="x_content">
                @*<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>*@
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title"># </th>
                                <th class="column-title">用户名 </th>
                                <th class="column-title">备注 </th>
                                <th class="column-title">添加时间 </th>
                                <th class="column-title">操作 </th>
                                <th class="bulk-actions" colspan="6">
                                    <a class="antoo" style="color:#fff; font-weight:500;">
                                        已选中 <span class="action-cnt"> </span>
                                        <i class="fa fa-chevron-down"></i>
                                    </a>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.AdminUserInfoList)
                            {
                                <tr class="pointer">
                                    <td class="a-center ">
                                        <input type="checkbox" class="flat table_records" name="ids" form="deleteForm" value="@item.Id">
                                    </td>
                                    <td class=" "> @item.Id</td>
                                    <td class=" ">@item.UserName </td>
                                    <td class=" ">@item.Note </td>
                                    <td class=" "> @item.AddTime.ToString("yyyy-MM-dd HH:mm")</td>
                                    <td class=" ">
                                        <a asp-page="Edit" asp-route-id="@item.Id" title="编辑" class="btn-xs btn btn-info">
                                            <em class="fa fa-pencil-square-o">编辑</em>
                                        </a>
                                        <a asp-page="AuthorizationPage" asp-route-accountId="@item.Id" title="设置角色" class="btn-xs btn btn-info">
                                            <em class="fa fa-gear">设置角色</em>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="text-center p jpagerbar">
                    @Html.Raw((Html.PagerBar(Model.AdminUserInfoList, new PagerBarSettings(Url.Page("/AdminUserInfo/Index", new
       {
           pageIndex = "{0}"
       }))
       {
           NoRecordTip = "暂无数据",
           ShowTotalCount = true
       })))
                </div>
            </div>
        </div>
    </div>
</div>
<form method="post" asp-page-handler="Delete" id="deleteForm"></form>